name: Build and Release Binaries

on:
  release:
    types: [created]

jobs:
  build:
    name: Build Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: aw-watcher-lastfm-linux
          - os: macos-latest
            artifact_name: aw-watcher-lastfm-macos
          - os: windows-latest
            artifact_name: aw-watcher-lastfm-windows.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build project
      run: cargo build --release

    - name: Rename binary
      shell: bash
      run: |
        cd target/release
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          mv aw-watcher-lastfm.exe ${{ matrix.artifact_name }}
        else
          mv aw-watcher-lastfm ${{ matrix.artifact_name }}
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: target/release/${{ matrix.artifact_name }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          artifacts/aw-watcher-lastfm-linux/aw-watcher-lastfm-linux
          artifacts/aw-watcher-lastfm-macos/aw-watcher-lastfm-macos
          artifacts/aw-watcher-lastfm-windows.exe/aw-watcher-lastfm-windows.exe