name: Build and Release Binaries

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write
  issues: write
  pull-requests: write
  statuses: write
  

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build project
      run: cargo build --release

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-binary
        path: target/release/

    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.os }}-binary

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          target/release/*
